### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by NaraSakamoto** [adilamarcelefreitas/SAP011-fleet-management-api#1]
Adila,

Deixo aqui algumas sugestões para você continuar a sua jornada de estudos!

Para continuar se aprimorando como Desenvolvedora Java e React, sugiro se aprofundar em:

1. Linguagem Java e Javascript. E para isso deixo algumas sugestões de estudo prático para você escolher:

 - [ ] [exercism](https://exercism.org/tracks/java)
 - [ ] [Code Academy](https://www.codecademy.com/learn/learn-java)
 - [ ] [Hacker Rank](https://www.hackerrank.com/domains/java)
 
2.   Conceitos de Programação Orientada a Objetos. Sugiro alguns cursos gratuitos, escolha um para fazer:

 - [ ] [Fundação Bradesco](https://www.ev.org.br/cursos/introducao-a-programacao-orientada-a-objetos-poo).
 - [ ] [Dev Dojo - Maratona Java](https://youtu.be/VKjFuX91G5Q?feature=shared). Esse curso é bem atual, vale a pena. 
 
3. Se aprofundar na construção de APIs REST usando Spring Boot, inclusive finalizando o projeto Fleet Management. Caso queira fazer outras APIs, vc pode tentar construir a API do Burguer Queen usando Spring Boot e Java! Deixei o link aqui em baixo. Deixei também um link com idéias de APIs para vc construir. E caso precise, para te apoiar nessas construções, aqui tem também alguns cursos gratuitos.

 - [ ] [Spring Boot 3 | Complete Course 2023](https://www.youtube.com/watch?v=wlYvA2b1BWI).
 - [ ] [Desafio Vagas: API de tarefas com Spring Boot!](https://www.youtube.com/watch?v=IjProDV001o). Esse vídeo a apresentadora mostra um desafio de uma vaga de emprego.
 - [ ] [Dev Dojo - Spring Boot Essentials 2](https://youtube.com/playlist?list=PL62G310vn6nFBIxp6ZwGnm8xMcGE3VA5H&feature=shared)
 - [ ] [Burguer Queen API](https://github.com/Laboratoria/SAP011-burger-queen-api)
 - [ ] [Ideias de projetos backend para você praticar - Jéssica Nathany](https://jessicanathanyf.medium.com/ideias-de-projetos-backend-para-voc%C3%AA-praticar-73022c3f36dc)
 - [ ] [Backend Challenges](https://github.com/CollabCodeTech/backend-challenges). Aqui vc encontra alguns desafios técnicos disponibilizados por empresas. Podem servir como idéias de API também. 

4. Inicie seus estudos em Bancos de Dados Relacionais e SQL. Foque na manutenção do dado (criação de tabelas, inserção de dados, atualização e deleção) e na criação de consultas (queries). 
- [ ] [Introdução a SQL: Consulta e gerenciamento de dados - Kha Academy](https://pt.khanacademy.org/computing/computer-programming/sql)
- [ ] [SQL Tutorial](https://www.w3schools.com/sql/)
- [ ] [Exercícios SQL - Hacker Rank](https://www.hackerrank.com/domains/sql)
- [ ] [Exercícios SQL - BeeCrowd](https://www.beecrowd.com.br/judge/en/problems/index/9)

5. Inicie seus estudos em React. Primeiro faça algum curso completo e então parta para a prática fazendo projetos! Comece pelo Movie Challenge, mas também deixo outras sugestões. 
- [ ] [Curso de React - Matheus Battisti](https://www.youtube.com/watch?v=FXqX7oof0I4&list=PLnDvRpP8BneyVA0SZ2okm-QBojomniQVO)
- [ ] [Laboratoria/SAP011-movie-challenge-fw](https://github.com/Laboratoria/SAP011-movie-challenge-fw)
- [ ] [80 ideias de projetos para usar no seu portfolio](https://www.linkedin.com/pulse/80-ideias-de-projetos-para-usar-seu-portfolio-leticia-coelho/?originalSubdomain=pt)

Revisando os seus Objetivos de Aprendizagem de cada um dos projetos da Laboratória, deixo aqui algumas sugestões de estudos que podem complementar o seu aprendizado.
 
Sobre HTML Semântico, veja um pouco sobre isso nesses conteúdos abaixo, mas pratique! Tente aplicar em seus próximos HTMLs:
- [ ] [Devmedia HTML Semântico](https://www.devmedia.com.br/html-semantico-conheca-os-elementos-semanticos-da-html5/38065)
- [ ] [Elementos semânticos do HTML5 explicados](https://www.freecodecamp.org/portuguese/news/elementos-semanticos-do-html5-explicados/)

Sobre recursão: 
- [ ] [Substituir laços usando recursão - FreeCodeCamp](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/basic-javascript/replace-loops-using-recursion)
- [ ] [Usar recursão para criar uma contagem regressiva - FreeCodeCamp](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown)
- [ ] [Usar recursão para criar um intervalo de números - FreeCodeCamp](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-range-of-numbers)
- [ ] [Exercícios de Recursão - HackerRank](https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=recursion)

Sobre Interfaces Java: 
- [ ]  Você pode iniciar seus estudos por esses conteúdos que deixo abaixo:
    - [ ]  [POO em Java - Compreendendo as Interfaces](https://www.dio.me/articles/poo-em-java-compreendendo-as-interfaces)
    - [ ]  [Interfaces em Java explicadas com exemplos](https://www.freecodecamp.org/portuguese/news/interfaces-em-java-explicadas-com-exemplos/)
    - [ ]  [Exercício sobre Interfaces - Exercism](https://exercism.org/tracks/java/concepts/interfaces)
    - [ ]  [Interfaces - Java Documentation](https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html)
    
Parabéns pela sua jornada ao longo do Bootcamp, Ádila! Você aproveitou bastante todas as oportunidades de aprendizagem!
Foi só o começo da sua carreira de sucesso na Tecnologia!

Beijos!
